### PR TITLE
Filter class features by the name query parameter

### PR DESCRIPTION
**Pull request by BenDMyers**
## What does this do?
This PR adds the `name` query parameter to the `/features` endpoint, so you can filter class features by their name.

## How was it tested?
Manually, as well as with the automated tests. I added tests to `server.itest.js` that test this endpoint with the parameter. Please let me know if more tests would be appropriate!

## Is there a Github issue this is resolving?
No, not that I know of.

## Here's a fun image for your troubles
An adorable dog in a cute sweater stares up at the camera

### CODE REVIEW

**Comment by bagelbits** [comment]
Can you add integration tests for this? You should be able to find examples in [this file](https://github.com/bagelbits/5e-srd-api/blob/master/src/tests/integration/server.itest.js)

**Comment by bagelbits** [comment]
I think you forgot to commit the tests. :D

**Comment by BenDMyers** [comment]
Ah, yep, I absolutely did!

**Review by bagelbits — APPROVED** [review]
LGTM

**Pull request merged**
